import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    target: 'node18',
    lib: {
      entry: resolve(__dirname, 'src/cli/index.ts'),
      name: 'taskflow',
      formats: ['cjs'],
      fileName: () => 'index.js',
    },
    rollupOptions: {
      external: [
        'npm',
        'node_modules/*',
        'chalk',
        'commander',
        'inquirer',
        'dotenv',
        'conf',
        'express',
        'cors',
        'jsonwebtoken',
        'marked',
        'highlight.js',
        'figlet',
        'ora',
        'winston',
        'js-yaml',
        'fs-extra',
        'fs/promises',
        'path',
        'os',
        'http',
        'https',
        'url',
        'crypto',
        'events',
        'stream',
        'util',
        'zlib',
        'buffer',
        'querystring',
        'net',
        'tls',
        'dns',
        'child_process',
        'process',
      ],
      output: {
        inlineDynamicImports: true,
      },
    },
    minify: 'terser',
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
    },
    sourcemap: false,
    chunkSizeWarningLimit: 1500,
  },
});
