import { getLogger } from '../../utils/logger';
/**
 * 问答处理器
 */

import { RetrievedChunk, QAResult, Source } from '../types';
const logger = getLogger('knowledge/retrieval/qa');


export class QAProcessor {
  async answer(question: string, chunks: RetrievedChunk[]): Promise<QAResult> {
    const startTime = Date.now();

    const context = this.buildContext(chunks);
    const answer = this.generateAnswer(question, context);
    const sources = this.buildSources(chunks);
    const confidence = this.calculateConfidence(chunks);

    return {
      answer,
      sources,
      confidence,
      latency: Date.now() - startTime,
    };
  }

  private buildContext(chunks: RetrievedChunk[]): string {
    return chunks.map((result, index) => `[${index + 1}] ${result.chunk.content}`).join('\n\n');
  }

  private generateAnswer(question: string, context: string): string {
    const relevantInfo = context.slice(0, 500);
    return `Based on the retrieved information:\n\n${relevantInfo}\n\n[Note: This is a simplified answer. In production, this would be generated by an AI model.]\n\nQuestion: ${question}`;
  }

  private buildSources(chunks: RetrievedChunk[]): Source[] {
    const sourceMap = new Map<string, Source>();

    for (const result of chunks) {
      const docId = result.chunk.documentId;

      if (!sourceMap.has(docId)) {
        sourceMap.set(docId, {
          documentId: docId,
          title: (result.chunk.metadata as any).title || 'Unknown',
          content: result.chunk.content,
          score: result.score,
          metadata: result.chunk.metadata,
        });
      }
    }

    return Array.from(sourceMap.values());
  }

  private calculateConfidence(chunks: RetrievedChunk[]): number {
    if (chunks.length === 0) return 0;
    const avgScore = chunks.reduce((sum, c) => sum + c.score, 0) / chunks.length;
    return Math.min(avgScore * 1.2, 1);
  }
}
